pulsar-edit/pulsar-chocolatey

README.md
Since the majority of the details of this release will already brought in via #3 this diff is very very small, whereas normally we would expect to see things like the SHASUM being updated etc.
Otherwise, I've removed a line from the README.md that mentioned manually changing the ReleaseNotes, but that is now done automatically, thanks again to @il-mix
=> [1.104.0] Release

.github/workflows/draft_publish.yml, README.md
This PR is simplistic, meant to be the final glue in all the recent changes.
This PR adds steps detailing how everything should work into the README.md, as well as adding a small nice to have, that the automatically created PR will close the issue that opened it. Just to reduce cleanup.
=> Tying all our new CI together

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
This PR drafts the 1.106.0 release of Pulsar.
Which is now awaiting moderation from the chocolatey team.
=> [1.106.0] Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.107.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.107.1] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.108.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.109.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.110.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.111.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.112.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.113.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/LICENSE.txt, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.114.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.115.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.116.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.117.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.118.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.119.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.120.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.121.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.122.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.123.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.124.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.125.0] Draft Release

pulsar/pulsar.nuspec, pulsar/tools/VERIFICATION.txt, pulsar/tools/chocolateyinstall.ps1
=> [1.130.0] Draft Release
